#!/bin/python3

import os
import sys
import math

#
# Complete the primeCount function below.
#
def primeCount(n):
    N = 80
    prime = [True for i in range(N+1)]   #storing all elements as true
    
    p = 2
    while(p * p <= N): 
        if (prime[p] == True): 
            for i in range(p * 2, N + 1, p):   #making all element as false which is multiple of 'p'
                prime[i] = False
        p += 1
    count = 0
    mul = 1 
    for p in range(2, N+1): 
        if(prime[p]):
            if(mul * p <= n): 
                mul *= p
                count += 1
            else:
                break
    return count 


if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    q = int(input())

    for q_itr in range(q):
        n = int(input())

        result = primeCount(n)

        fptr.write(str(result) + '\n')

    fptr.close()
